name:  Bugs
description: Colabora con el mejoramiento general o especifico de la p谩gina y su entorno al reportar bugs.
title: "[Bug]: Titulo necesario"
labels: ["Bugs"]
assignees:
  - DisoQ
body:
  - type: dropdown
    id: tipoM
    attributes:
      label: Tipo de error encontrado
      description: Seleccione el tipo de error que se hall贸.
      options:
        - Error de carga
        - Rutas erroneas
        - Escritura / Redacci贸n
        - Otro
    validations:
      required: true

  - type: input
    id: discordM
    attributes:
      label: Usuario de Discord
      description: Detalla aqu铆 la informaci贸n de tu usuario en Discord
      placeholder: DisoQ#1693 (ID:379375263022317584)
    validations:
      required: true

  - type: textarea
    id: contenidoM
    attributes:
      label: Contenido del error
      description: Detalla el problema lo m谩ximo posible; en lo posible los pasos para la obtenci贸n del error.
      placeholder: Recuerda que este espacio soporta la sintaxis Markdown.
    validations:
      required: true
